name: design_all
description: İç Mimarlık Proje ve Tasarım Asistanı
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Tasarım & İkonlar
  lucide_icons: ^0.320.0
  google_fonts: ^6.1.0
  # Backend & State
  supabase_flutter: ^2.0.2
  flutter_riverpod: ^2.4.9
  # Özellikler
  image_picker: ^1.0.7
  palette_generator: ^0.3.3+3

flutter:
  uses-material-design: true
  assets:
    - assets/images/